### ISSUE TITLE
The default vagrant box is very old

### ISSUE THREAD

**Issue by byroncollins** [cdaf/linux#16]
I'm having issues trying with these vagrant boxes and my virtualbox installation of 6.1.32

have installed vbguest plugin but only the build VM is able to run the updated guest additions

`
C:\Users\byronc\git\cdaf\linux>vagrant vbguest --status

OVERRIDE_IMAGE not specified, random box is cdaf/Ubuntu18

[linux-1] GuestAdditions seems to be installed (6.1.32) correctly, but not running.

[build] GuestAdditions 6.1.32 running --- OK.
`
Is there any chance that the "randbom box" cdaf/Ubuntu18 can be updated or a Ubuntu20 box released?

**Comment by cdaf** [comment]
It's quite out of date, I'll rebuild and publish an update, along with a new publication of Ubuntu20

**Comment by cdaf** [comment]
I just realised, it appears you are trying to run the regression test vagrantfile (which is paired with the jenkinsfile), which isn't used for box construction.

The published image is https://app.vagrantup.com/cdaf/boxes/Ubuntu18. Although an older version of the GuestAdditions is used it should work with the latest VirtualBox software. Please test and advise that this works for you.

p.s. I'm releasing an updated Windows Server 2016 today, hope to release Ubuntu 20.04 tomorrow.

**Comment by cdaf** [comment]
Ubuntu 20.04 does not work with Vagrant/Hyper-V the same way 18.04 did, so it may take me some time get it working.

Note: the vagrantfile in the root of this repo is for nightly automated regression testing of CDAF itself. If you want to review the vagrantfile used for constructing the images, see here https://github.com/cdaf/linux/blob/master/samples/vagrant-box/Vagrantfile (at build time the appropriate provider is uncommented).

**Comment by cdaf** [comment]
cdaf/Ubuntu20 has now been released. If you are looking for a sample vagrantfile to use with this box, please see here for the vagrantfile I use

https://github.com/cdaf/linux/tree/master/samples/vagrant-test

I'm not starting on the refresh of 18.04

**Comment by cdaf** [comment]
cdaf/Ubuntu18 has now also been released.
